name: 'Terraform Destroy'

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment:
      name: development  # Use an environment with protection rules if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::943169211906:role/Githubconnect
          role-session-name: githubworkflowsession
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_LOG: ERROR

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_LOG: ERROR
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}